# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/polon/Desktop/Master-Research

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/polon/Desktop/Master-Research

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/polon/Desktop/Master-Research/CMakeFiles /home/polon/Desktop/Master-Research//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/polon/Desktop/Master-Research/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SOURCE_FILES

# Build rule for target.
SOURCE_FILES: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SOURCE_FILES
.PHONY : SOURCE_FILES

# fast build rule for target.
SOURCE_FILES/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/build
.PHONY : SOURCE_FILES/fast

#=============================================================================
# Target rules for targets named GraphPartitioning

# Build rule for target.
GraphPartitioning: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GraphPartitioning
.PHONY : GraphPartitioning

# fast build rule for target.
GraphPartitioning/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphPartitioning.dir/build.make CMakeFiles/GraphPartitioning.dir/build
.PHONY : GraphPartitioning/fast

converter/conversions.o: converter/conversions.cpp.o
.PHONY : converter/conversions.o

# target to build an object file
converter/conversions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/converter/conversions.cpp.o
.PHONY : converter/conversions.cpp.o

converter/conversions.i: converter/conversions.cpp.i
.PHONY : converter/conversions.i

# target to preprocess a source file
converter/conversions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/converter/conversions.cpp.i
.PHONY : converter/conversions.cpp.i

converter/conversions.s: converter/conversions.cpp.s
.PHONY : converter/conversions.s

# target to generate assembly for a file
converter/conversions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/converter/conversions.cpp.s
.PHONY : converter/conversions.cpp.s

converter/shuffler.o: converter/shuffler.cpp.o
.PHONY : converter/shuffler.o

# target to build an object file
converter/shuffler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/converter/shuffler.cpp.o
.PHONY : converter/shuffler.cpp.o

converter/shuffler.i: converter/shuffler.cpp.i
.PHONY : converter/shuffler.i

# target to preprocess a source file
converter/shuffler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/converter/shuffler.cpp.i
.PHONY : converter/shuffler.cpp.i

converter/shuffler.s: converter/shuffler.cpp.s
.PHONY : converter/shuffler.s

# target to generate assembly for a file
converter/shuffler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/converter/shuffler.cpp.s
.PHONY : converter/shuffler.cpp.s

dbh.o: dbh.cpp.o
.PHONY : dbh.o

# target to build an object file
dbh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/dbh.cpp.o
.PHONY : dbh.cpp.o

dbh.i: dbh.cpp.i
.PHONY : dbh.i

# target to preprocess a source file
dbh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/dbh.cpp.i
.PHONY : dbh.cpp.i

dbh.s: dbh.cpp.s
.PHONY : dbh.s

# target to generate assembly for a file
dbh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/dbh.cpp.s
.PHONY : dbh.cpp.s

hdrf.o: hdrf.cpp.o
.PHONY : hdrf.o

# target to build an object file
hdrf.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/hdrf.cpp.o
.PHONY : hdrf.cpp.o

hdrf.i: hdrf.cpp.i
.PHONY : hdrf.i

# target to preprocess a source file
hdrf.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/hdrf.cpp.i
.PHONY : hdrf.cpp.i

hdrf.s: hdrf.cpp.s
.PHONY : hdrf.s

# target to generate assembly for a file
hdrf.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/hdrf.cpp.s
.PHONY : hdrf.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphPartitioning.dir/build.make CMakeFiles/GraphPartitioning.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphPartitioning.dir/build.make CMakeFiles/GraphPartitioning.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GraphPartitioning.dir/build.make CMakeFiles/GraphPartitioning.dir/main.cpp.s
.PHONY : main.cpp.s

memory.o: memory.cpp.o
.PHONY : memory.o

# target to build an object file
memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/memory.cpp.o
.PHONY : memory.cpp.o

memory.i: memory.cpp.i
.PHONY : memory.i

# target to preprocess a source file
memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/memory.cpp.i
.PHONY : memory.cpp.i

memory.s: memory.cpp.s
.PHONY : memory.s

# target to generate assembly for a file
memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/memory.cpp.s
.PHONY : memory.cpp.s

memory_for_pre.o: memory_for_pre.cpp.o
.PHONY : memory_for_pre.o

# target to build an object file
memory_for_pre.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/memory_for_pre.cpp.o
.PHONY : memory_for_pre.cpp.o

memory_for_pre.i: memory_for_pre.cpp.i
.PHONY : memory_for_pre.i

# target to preprocess a source file
memory_for_pre.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/memory_for_pre.cpp.i
.PHONY : memory_for_pre.cpp.i

memory_for_pre.s: memory_for_pre.cpp.s
.PHONY : memory_for_pre.s

# target to generate assembly for a file
memory_for_pre.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/memory_for_pre.cpp.s
.PHONY : memory_for_pre.cpp.s

ne_partitioner/graph.o: ne_partitioner/graph.cpp.o
.PHONY : ne_partitioner/graph.o

# target to build an object file
ne_partitioner/graph.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/ne_partitioner/graph.cpp.o
.PHONY : ne_partitioner/graph.cpp.o

ne_partitioner/graph.i: ne_partitioner/graph.cpp.i
.PHONY : ne_partitioner/graph.i

# target to preprocess a source file
ne_partitioner/graph.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/ne_partitioner/graph.cpp.i
.PHONY : ne_partitioner/graph.cpp.i

ne_partitioner/graph.s: ne_partitioner/graph.cpp.s
.PHONY : ne_partitioner/graph.s

# target to generate assembly for a file
ne_partitioner/graph.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/ne_partitioner/graph.cpp.s
.PHONY : ne_partitioner/graph.cpp.s

ne_partitioner/ne.o: ne_partitioner/ne.cpp.o
.PHONY : ne_partitioner/ne.o

# target to build an object file
ne_partitioner/ne.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/ne_partitioner/ne.cpp.o
.PHONY : ne_partitioner/ne.cpp.o

ne_partitioner/ne.i: ne_partitioner/ne.cpp.i
.PHONY : ne_partitioner/ne.i

# target to preprocess a source file
ne_partitioner/ne.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/ne_partitioner/ne.cpp.i
.PHONY : ne_partitioner/ne.cpp.i

ne_partitioner/ne.s: ne_partitioner/ne.cpp.s
.PHONY : ne_partitioner/ne.s

# target to generate assembly for a file
ne_partitioner/ne.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/ne_partitioner/ne.cpp.s
.PHONY : ne_partitioner/ne.cpp.s

pre_processing.o: pre_processing.cpp.o
.PHONY : pre_processing.o

# target to build an object file
pre_processing.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/pre_processing.cpp.o
.PHONY : pre_processing.cpp.o

pre_processing.i: pre_processing.cpp.i
.PHONY : pre_processing.i

# target to preprocess a source file
pre_processing.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/pre_processing.cpp.i
.PHONY : pre_processing.cpp.i

pre_processing.s: pre_processing.cpp.s
.PHONY : pre_processing.s

# target to generate assembly for a file
pre_processing.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/pre_processing.cpp.s
.PHONY : pre_processing.cpp.s

storage.o: storage.cpp.o
.PHONY : storage.o

# target to build an object file
storage.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/storage.cpp.o
.PHONY : storage.cpp.o

storage.i: storage.cpp.i
.PHONY : storage.i

# target to preprocess a source file
storage.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/storage.cpp.i
.PHONY : storage.cpp.i

storage.s: storage.cpp.s
.PHONY : storage.s

# target to generate assembly for a file
storage.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/storage.cpp.s
.PHONY : storage.cpp.s

streaming_vp/fennel.o: streaming_vp/fennel.cpp.o
.PHONY : streaming_vp/fennel.o

# target to build an object file
streaming_vp/fennel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/streaming_vp/fennel.cpp.o
.PHONY : streaming_vp/fennel.cpp.o

streaming_vp/fennel.i: streaming_vp/fennel.cpp.i
.PHONY : streaming_vp/fennel.i

# target to preprocess a source file
streaming_vp/fennel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/streaming_vp/fennel.cpp.i
.PHONY : streaming_vp/fennel.cpp.i

streaming_vp/fennel.s: streaming_vp/fennel.cpp.s
.PHONY : streaming_vp/fennel.s

# target to generate assembly for a file
streaming_vp/fennel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/streaming_vp/fennel.cpp.s
.PHONY : streaming_vp/fennel.cpp.s

streaming_vp/ldg.o: streaming_vp/ldg.cpp.o
.PHONY : streaming_vp/ldg.o

# target to build an object file
streaming_vp/ldg.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/streaming_vp/ldg.cpp.o
.PHONY : streaming_vp/ldg.cpp.o

streaming_vp/ldg.i: streaming_vp/ldg.cpp.i
.PHONY : streaming_vp/ldg.i

# target to preprocess a source file
streaming_vp/ldg.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/streaming_vp/ldg.cpp.i
.PHONY : streaming_vp/ldg.cpp.i

streaming_vp/ldg.s: streaming_vp/ldg.cpp.s
.PHONY : streaming_vp/ldg.s

# target to generate assembly for a file
streaming_vp/ldg.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/SOURCE_FILES.dir/build.make CMakeFiles/SOURCE_FILES.dir/streaming_vp/ldg.cpp.s
.PHONY : streaming_vp/ldg.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... GraphPartitioning"
	@echo "... SOURCE_FILES"
	@echo "... converter/conversions.o"
	@echo "... converter/conversions.i"
	@echo "... converter/conversions.s"
	@echo "... converter/shuffler.o"
	@echo "... converter/shuffler.i"
	@echo "... converter/shuffler.s"
	@echo "... dbh.o"
	@echo "... dbh.i"
	@echo "... dbh.s"
	@echo "... hdrf.o"
	@echo "... hdrf.i"
	@echo "... hdrf.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... memory.o"
	@echo "... memory.i"
	@echo "... memory.s"
	@echo "... memory_for_pre.o"
	@echo "... memory_for_pre.i"
	@echo "... memory_for_pre.s"
	@echo "... ne_partitioner/graph.o"
	@echo "... ne_partitioner/graph.i"
	@echo "... ne_partitioner/graph.s"
	@echo "... ne_partitioner/ne.o"
	@echo "... ne_partitioner/ne.i"
	@echo "... ne_partitioner/ne.s"
	@echo "... pre_processing.o"
	@echo "... pre_processing.i"
	@echo "... pre_processing.s"
	@echo "... storage.o"
	@echo "... storage.i"
	@echo "... storage.s"
	@echo "... streaming_vp/fennel.o"
	@echo "... streaming_vp/fennel.i"
	@echo "... streaming_vp/fennel.s"
	@echo "... streaming_vp/ldg.o"
	@echo "... streaming_vp/ldg.i"
	@echo "... streaming_vp/ldg.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

